# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zc702:part0:1.0 [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_verilog -library xil_defaultlib /home/jared/Research/vivado_workspace/scanline_buffer/vivado/project_1.srcs/sources_1/imports/vivado/scanline_buffer_v1_0.v
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/jared/Research/vivado_workspace/scanline_buffer/vivado/project_1.cache/wt [current_project]
set_property parent.project_dir /home/jared/Research/vivado_workspace/scanline_buffer/vivado [current_project]
catch { write_hwdef -file scanline_buffer_v1_0.hwdef }
synth_design -top scanline_buffer_v1_0 -part xc7z020clg484-1
write_checkpoint scanline_buffer_v1_0.dcp
report_utilization -file scanline_buffer_v1_0_utilization_synth.rpt -pb scanline_buffer_v1_0_utilization_synth.pb
